### ISSUE TITLE
Cannot start rodeo server (0.3.0)

### ISSUE THREAD

**Issue by danybol** [yhat/rodeo#91]
Running 
```bash
rodeo .
```
Leads to the following error:
```
[ERROR]: Exception on / [GET]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/rodeo/rodeo.py", line 23, in home
    pip.utils.pkg_resources = imp.reload(pip.utils.pkg_resources)
AttributeError: 'module' object has no attribute 'utils'
````

This occurs on Mac OS X Yosemite, Python 2.7.8

**Comment by willpitchers** [comment]
Hey - I have the exact same issue as danybol.

I am also running OSX Yosemite (10.10.03) and Python 2.7.8

Any advice appreciated.

**Comment by juraseg** [comment]
Hi guys

I had the same problem on OSX (though I use Maverick). Upgrading pip helped me. Try:
pip install --upgrade pip

**Comment by roshannair** [comment]
Same issue. This happened with python 2.7 and pip 1.5.4. Running pip install -U pip fixed it (this upgraded it to pip-6.1.1)

**Comment by tssan** [comment]
I had same problem and after pip update having next one regarding slugify.

```
Traceback (most recent call last):
  File "/Users/tssan/.virtualenvs/trash/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/tssan/.virtualenvs/trash/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/tssan/.virtualenvs/trash/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/tssan/.virtualenvs/trash/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/tssan/.virtualenvs/trash/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/tssan/.virtualenvs/trash/lib/python2.7/site-packages/rodeo/rodeo.py", line 38, in home
    parent_dirslug = slugify.slugify(parent_dir)
AttributeError: 'function' object has no attribute 'slugify'
```

**Comment by juraseg** [comment]
Hi tssan

Had the same issue. Happens due to latest commit, where `slugify` function was moved to another module, 2 of 3 usages where fixed properly. I've created pull requests for this bug - https://github.com/yhat/rodeo/pull/93. Still under review

**Comment by John-Brown** [comment]
I am also getting the error.
>AttributeError: 'function' object has no attribute 'slugify'

**Comment by glamp** [comment]
ok fixed now

**Comment by dyngts** [comment]
After upgrade rodeo to 0.3.3, it's raise an error again like this

```
Created new window in existing browser session.
[ERROR]: Exception on /rc [GET]
Traceback (most recent call last):
  File "/home/hadyan/anaconda/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hadyan/anaconda/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hadyan/anaconda/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hadyan/anaconda/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hadyan/anaconda/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hadyan/anaconda/lib/python2.7/site-packages/rodeo/rodeo.py", line 118, in rc
    except FileNotFoundError:
NameError: global name 'FileNotFoundError' is not defined
```

**Comment by willpitchers** [comment]
The pip update fixed the original error, but now (version 0.3.4) there's a different error state:

2015-05-06 17:11:03.234 osascript[6207:280290] Error loading /Library/ScriptingAdditions/Adobe Unit Types.osax/Contents/MacOS/Adobe Unit Types:  dlopen(/Library/ScriptingAdditions/Adobe Unit Types.osax/Contents/MacOS/Adobe Unit Types, 262): no suitable image found.  Did find:
	/Library/ScriptingAdditions/Adobe Unit Types.osax/Contents/MacOS/Adobe Unit Types: no matching architecture in universal wrapper
osascript: OpenScripting.framework - scripting addition "/Library/ScriptingAdditions/Adobe Unit Types.osax" declares no loadable handlers.
[ERROR]: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/site-packages/rodeo/rodeo.py", line 70, in home
    file_tree=file_tree, version=__version__)
  File "/usr/local/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/usr/local/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/rodeo/templates/index.html", line 185, in top-level template code
    <a id="file-{{ f.dirname }}" data-parnet-slug="{{ f.parentslug }}" data-dirname="{{ f.dirslug }}" href="#" class="list-group-item {{ f.parentslug }} showdir">
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 9: ordinal not in range(128)

**Comment by grubsa** [comment]
Getting a similar error:

[ERROR]: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/site-packages/rodeo/rodeo.py", line 71, in home
    file_tree=file_tree, version=__version__)
  File "/usr/local/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/usr/local/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/rodeo/templates/index.html", line 185, in top-level template code
    <a id="file-{{ f.dirname }}" data-parnet-slug="{{ f.parentslug }}" data-dirname="{{ f.dirslug }}" href="#" class="list-group-item {{ f.parentslug }} showdir">
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd7 in position 0: ordinal not in range(128)


Running Yosemite 10.10.2
pip 6.1.1
rodeo 0.3.6
python 2.7.9
ipython 3.0.0

**Comment by glamp** [comment]
df824e6ed3d467a303dcd0c6871e18cb7603e4a0

**Comment by jeanpat** [comment]
Still the same error with rodeo 0.4.2 on ubuntu 15.04:

      File "/usr/local/lib/python2.7/dist-packages/rodeo/templates/index.html", line 34, in top-level template code
        {% include 'bottom-right.html' %}
      File "/usr/local/lib/python2.7/dist-packages/rodeo/templates/bottom-right.html", line 17, in  top-level template code
        <a id="file-{{ f.dirname }}" data-parnet-slug="{{ f.parentslug }}" data-dirname="{{ f.dirslug }}" 
href="#" class="list-group-item {{ f.parentslug }} showdir">
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3: ordinal not in range(128)

**Comment by grubsa** [comment]
@glamp Works for me! looks nice. Will finally get a chance to play with it.

**Comment by glamp** [comment]
What filename do you have that has non-ascii characters in it?

**Comment by jeanpat** [comment]
Still cannot start rodeo under ubuntu 15.04:

	~$ sudo pip install rodeo --upgrade
		The directory '/home/jeanpat/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
		The directory '/home/jeanpat/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
		Collecting rodeo
		Requirement already up-to-date: mistune in /usr/local/lib/python2.7/dist-packages (from rodeo)
		Requirement already up-to-date: ipython>=3.0.0 in /usr/local/lib/python2.7/dist-packages (from rodeo)
		Requirement already up-to-date: docopt in /usr/local/lib/python2.7/dist-packages (from rodeo)
		Requirement already up-to-date: pyzmq>=13 in /usr/local/lib/python2.7/dist-packages (from rodeo)
		Requirement already up-to-date: Flask>=0.10.1 in /usr/local/lib/python2.7/dist-packages (from rodeo)
		Requirement already up-to-date: Werkzeug>=0.7 in /usr/local/lib/python2.7/dist-packages (from Flask>=0.10.1->rodeo)
		Requirement already up-to-date: Jinja2>=2.4 in /usr/local/lib/python2.7/dist-packages (from Flask>=0.10.1->rodeo)
		Requirement already up-to-date: itsdangerous>=0.21 in /usr/local/lib/python2.7/dist-packages (from Flask>=0.10.1->rodeo)
		Requirement already up-to-date: markupsafe in /usr/local/lib/python2.7/dist-packages (from Jinja2>=2.4->Flask>=0.10.1->rodeo)
		Installing collected packages: rodeo
		Successfully installed rodeo-0.4.3

then if rodeo is run as follow:

	~$ rodeo .
	
	 _______      ___   ______   ________    ___    
	|_   __ \   .'   `.|_   _ `.|_   __  | .'   `.  
	  | |__) | /  .-.  \ | | `. \ | |_ \_|/  .-.  \ 
	  |  __ /  | |   | | | |  | | |  _| _ | |   | | 
	 _| |  \ \_\  `-'  /_| |_.' /_| |__/ |\  `-'  / 
	|____| |___|`.___.'|______.'|________| `.___.'  
	
	''''''''''''''''''''''''''''''''''''''''''''''''''
	  URL: http://localhost:5000/
	  DIRECTORY: /home/jeanpat
	''''''''''''''''''''''''''''''''''''''''''''''''''
	
	(process:4870): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
	[ERROR]: Exception on / [GET]
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
	    response = self.full_dispatch_request()
	  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
	    rv = self.handle_user_exception(e)
	  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
	    reraise(exc_type, exc_value, tb)
	  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
	    rv = self.dispatch_request()
	  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
	    return self.view_functions[rule.endpoint](**req.view_args)
	  File "/usr/local/lib/python2.7/dist-packages/rodeo/rodeo.py", line 79, in home
	    file_tree=file_tree, version=__version__)
	  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 128, in render_template
	    context, ctx.app)
	  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 110, in _render
	    rv = template.render(context)
	  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 969, in render
	    return self.environment.handle_exception(exc_info, True)
	  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 742, in handle_exception
	    reraise(exc_type, exc_value, tb)
	  File "/usr/local/lib/python2.7/dist-packages/rodeo/templates/index.html", line 34, in top-level template code
	    {% include 'bottom-right.html' %}
	  File "/usr/local/lib/python2.7/dist-packages/rodeo/templates/bottom-right.html", line 17, in top-level template code
	    <a id="file-{{ f.dirname }}" data-parnet-slug="{{ f.parentslug }}" data-dirname="{{ f.dirslug }}" href="#" class="list-group-item {{ f.parentslug }} showdir">
	UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3: ordinal not in range(128)

The guilty file `bottom-right.html` can be found here http://bit.ly/1JgbrMF

**Comment by willpitchers** [comment]
FYI, the latest version of Rodeo has fixed my issue! The IDE now launches and appears to run fine. ***Thanks!***

In case it's still useful, there is a non-critical error message:

|_   __ \   .'   `.|_   _ `.|_   __  | .'   `.  
  | |__) | /  .-.  \ | | `. \ | |_ \_|/  .-.  \ 
  |  __ /  | |   | | | |  | | |  _| _ | |   | | 
 _| |  \ \_\  `-'  /_| |_.' /_| |__/ |\  `-'  / 
|____| |___|`.___.'|______.'|________| `.___.'  

''''''''''''''''''''''''''''''''''''''''''''''''''
  URL: http://localhost:5000/
  DIRECTORY: /Volumes/Old_HD/DeSKToP/IN
''''''''''''''''''''''''''''''''''''''''''''''''''
2015-06-23 10:08:39.499 osascript[44938:8227732] Error loading /Library/ScriptingAdditions/Adobe Unit Types.osax/Contents/MacOS/Adobe Unit Types:  dlopen(/Library/ScriptingAdditions/Adobe Unit Types.osax/Contents/MacOS/Adobe Unit Types, 262): no suitable image found.  Did find:
	/Library/ScriptingAdditions/Adobe Unit Types.osax/Contents/MacOS/Adobe Unit Types: no matching architecture in universal wrapper
osascript: OpenScripting.framework - scripting addition "/Library/ScriptingAdditions/Adobe Unit Types.osax" declares no loadable handlers.

**Comment by ZarubinArtem** [comment]
pip up to date. Rodeo doesn't start. Any ideas? Thank you.

![screenshot 2015-12-30 09 55 30](https://cloud.githubusercontent.com/assets/7883191/12047379/84deebe4-aedb-11e5-9a36-1c133b682b1d.png)

![screenshot 2015-12-30 09 55 12](https://cloud.githubusercontent.com/assets/7883191/12047382/8beb9e1e-aedb-11e5-9999-1a343e456249.png)
